test coverage

diff --git a/.github/workflows/website.yml b/.github/workflows/website.yml
--- a/.github/workflows/website.yml
+++ b/.github/workflows/website.yml
@@ -20,7 +20,37 @@ jobs:
 
       - name: Install dependencies
         run: npm install
-
+      - name: Install Playwright browsers
+        run: npm playwright install
+      - name: Start Storybook
+        run: npm storybook --ci --port 6006 &
+      - name: Wait for Storybook to be available
+        run: npx wait-on http://127.0.0.1:6006
+      - name: Run tests with coverage
+        run: npm test-storybook --coverage
+      - name: Check coverage threshold
+        run: |
+          COVERAGE=$(grep -o '"statements": [0-9.]*' ./coverage/coverage-summary.json | awk '{print $2}')
+          if (( $(echo "$COVERAGE < 50.0" |bc -l) )); then
+            echo "Test coverage ($COVERAGE%) is below the required threshold of 50%."
+            exit 1
+          else
+            echo "Test coverage ($COVERAGE%) meets the required threshold."
+          fi
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v4
+        with:
+            token: ${{ secrets.CODECOV_TOKEN }}
+            files: ./coverage/lcov.info
+            flags: unittests
+            name: codecov-umbrella
+            fail_ci_if_error: true
+            verbose: true
+  
+      - name: Stop Storybook
+        run: kill $(lsof -t -i:6006)
+          # This command stops the Storybook process
+  
   deploy:
     runs-on: ubuntu-latest
     needs: build
